from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings

User = get_user_model()

class Vehicle(models.Model):
    vehicle_number = models.CharField(max_length=40, unique=True)
    model = models.CharField(max_length=120)
    manufacturer = models.CharField(max_length=120, default='')
    year = models.IntegerField(default=2025)
    vehicle_type = models.CharField(max_length=40, default='sedan')
    status = models.CharField(max_length=24, default='online')
    autonomy_level = models.IntegerField(default=3)
    driver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='vehicles')
    current_speed = models.FloatField(default=0)
    battery_level = models.IntegerField(default=88)
    odometer_km = models.FloatField(default=0)
    safety_score = models.IntegerField(default=92)
    lat = models.FloatField(default=12.9716)
    lng = models.FloatField(default=77.5946)
    heading = models.FloatField(default=0)
    ai_modules = models.JSONField(default=list)
    last_seen_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Trip(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    driver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    origin = models.CharField(max_length=160, default='')
    destination = models.CharField(max_length=160, default='')
    distance_km = models.FloatField(default=0)
    avg_speed = models.FloatField(default=0)
    max_speed = models.FloatField(default=0)
    safety_score = models.IntegerField(default=90)
    duration_min = models.IntegerField(default=0)
    status = models.CharField(max_length=24, default='completed')
    started_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(null=True, blank=True)

class Detection(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    module = models.CharField(max_length=48)
    label = models.CharField(max_length=96)
    confidence = models.FloatField(default=0)
    severity = models.CharField(max_length=24, default='normal')
    engine = models.CharField(max_length=40, default='YOLOv8')
    frame_ref = models.CharField(max_length=80, default='')
    meta = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)

class DriverStatus(models.Model):
    driver = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    attention = models.IntegerField(default=90)
    drowsiness = models.IntegerField(default=8)
    fatigue = models.IntegerField(default=12)
    phone_usage = models.IntegerField(default=0)
    seatbelt = models.BooleanField(default=True)
    eye_status = models.CharField(max_length=24, default='open')
    heart_rate = models.IntegerField(default=76)
    recorded_at = models.DateTimeField(auto_now_add=True)

class Accident(models.Model):
    code = models.CharField(max_length=32, unique=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    driver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    severity = models.CharField(max_length=24, default='warning')
    confidence = models.FloatField(default=0)
    impact_g = models.FloatField(default=0)
    airbag_deployed = models.BooleanField(default=False)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    address = models.CharField(max_length=220, default='')
    status = models.CharField(max_length=32, default='open')
    description = models.TextField(default='')
    response_time_sec = models.IntegerField(default=0)
    detected_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

class AccidentTimeline(models.Model):
    accident = models.ForeignKey(Accident, on_delete=models.CASCADE, related_name='timeline')
    step = models.IntegerField(default=0)
    label = models.CharField(max_length=120)
    description = models.TextField(default='')
    status = models.CharField(max_length=24, default='done')
    occurred_at = models.DateTimeField(auto_now_add=True)

class EmergencyContact(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=140)
    contact_type = models.CharField(max_length=32, default='family')
    relation = models.CharField(max_length=60, default='')
    phone = models.CharField(max_length=40, default='')
    address = models.CharField(max_length=220, default='')
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    distance_km = models.FloatField(default=0)
    eta_min = models.IntegerField(default=0)
    available = models.BooleanField(default=True)

class Dispatch(models.Model):
    accident = models.ForeignKey(Accident, null=True, blank=True, on_delete=models.SET_NULL)
    vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete=models.SET_NULL)
    service = models.CharField(max_length=40)
    status = models.CharField(max_length=32, default='dispatched')
    eta_min = models.IntegerField(default=6)
    notes = models.TextField(default='')
    created_at = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=160)
    message = models.TextField(default='')
    level = models.CharField(max_length=24, default='info')
    category = models.CharField(max_length=40, default='system')
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

class Report(models.Model):
    name = models.CharField(max_length=180)
    format = models.CharField(max_length=12, default='pdf')
    scope = models.CharField(max_length=40, default='accidents')
    filters = models.JSONField(default=dict)
    row_count = models.IntegerField(default=0)
    size_kb = models.IntegerField(default=0)
    status = models.CharField(max_length=24, default='ready')
    generated_by = models.CharField(max_length=120, default='system')
    created_at = models.DateTimeField(auto_now_add=True)

class Settings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    theme = models.CharField(max_length=24, default='midnight')
    accent = models.CharField(max_length=24, default='cyan')
    font_size = models.CharField(max_length=12, default='medium')
    units = models.CharField(max_length=12, default='metric')
    autonomy_level = models.IntegerField(default=3)
    ai_sensitivity = models.IntegerField(default=78)
    emergency_auto_dispatch = models.BooleanField(default=True)
    notify_email = models.BooleanField(default=True)
    notify_sms = models.BooleanField(default=True)
    notify_push = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    full_name = models.CharField(max_length=160)
    username = models.CharField(max_length=80, unique=True)
    email = models.EmailField(unique=True)
    mobile = models.CharField(max_length=40, default='')
    role = models.CharField(max_length=40, default='driver')
    vehicle_number = models.CharField(max_length=40, default='')
    avatar_url = models.CharField(max_length=500, default='')
    face_enrolled = models.BooleanField(default=False)
    fingerprint_enrolled = models.BooleanField(default=False)
    face_signature = models.CharField(max_length=64, default='')
    fingerprint_signature = models.CharField(max_length=64, default='')
    safety_score = models.IntegerField(default=92)
    status = models.CharField(max_length=24, default='active')
    last_login_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
