import { eq } from "drizzle-orm";
import { db } from "@/db";
import { users } from "@/db/schema";
import { fail, guard, ok } from "@/lib/api";

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  return guard(async () => {
    const body = (await request.json()) as { email?: string };
    const email = (body.email ?? "").trim().toLowerCase();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return fail("Enter a valid email address", 422, "validation_error", { email: "Invalid email" });
    }

    const [user] = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1);

    // Never disclose account existence — always return the same envelope.
    return ok({
      dispatched: true,
      channel: "email",
      resetWindowMinutes: 20,
      hint: user ? "Recovery link generated by the identity service." : "If the account exists a link was sent.",
    });
  });
}
